-- Inspection Routes — the automation primitive. One route = a named, scheduled,
-- ordered list of activos that, when "run", spawns a parent OT plus one sub-OT
-- per activo. Used for recurring rounds (weekly generator check, monthly HVAC,
-- etc.). Works in both subcontratista mode (scoped to a sociedad/client) and
-- propietario mode (sociedad_id stays null).

CREATE TABLE IF NOT EXISTS public.inspection_routes (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  workspace_id uuid NOT NULL REFERENCES public.workspaces(id) ON DELETE CASCADE,
  sociedad_id uuid REFERENCES public.sociedades(id) ON DELETE SET NULL,
  nombre text NOT NULL,
  descripcion text,
  tipo_trabajo text DEFAULT 'preventiva',
  prioridad text DEFAULT 'media',
  -- Schedule: reuses the existing recurrencia enum.
  recurrencia text DEFAULT 'semanal',
  recurrencia_config jsonb,
  next_due_at timestamptz,
  -- Defaults applied to every spawned sub-OT.
  default_asignados_ids uuid[] NOT NULL DEFAULT '{}',
  default_procedimiento_ids uuid[] NOT NULL DEFAULT '{}',
  requiere_fotos boolean NOT NULL DEFAULT true,
  requiere_hoja boolean NOT NULL DEFAULT false,
  requiere_materiales boolean NOT NULL DEFAULT false,
  activo_flag boolean NOT NULL DEFAULT true,
  created_at timestamptz NOT NULL DEFAULT now(),
  updated_at timestamptz NOT NULL DEFAULT now()
);
CREATE INDEX IF NOT EXISTS idx_inspection_routes_ws_soc
  ON public.inspection_routes (workspace_id, sociedad_id)
  WHERE activo_flag;
CREATE INDEX IF NOT EXISTS idx_inspection_routes_due
  ON public.inspection_routes (next_due_at)
  WHERE activo_flag AND next_due_at IS NOT NULL;

CREATE TABLE IF NOT EXISTS public.inspection_route_items (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  route_id uuid NOT NULL REFERENCES public.inspection_routes(id) ON DELETE CASCADE,
  activo_id uuid NOT NULL REFERENCES public.activos(id) ON DELETE CASCADE,
  orden int NOT NULL DEFAULT 0,
  notas text,
  -- Per-item overrides (NULL = inherit from route default).
  procedimiento_ids uuid[],
  asignados_ids uuid[],
  created_at timestamptz NOT NULL DEFAULT now()
);
CREATE INDEX IF NOT EXISTS idx_inspection_route_items_route
  ON public.inspection_route_items (route_id, orden);
CREATE INDEX IF NOT EXISTS idx_inspection_route_items_activo
  ON public.inspection_route_items (activo_id);

-- Backlink: each OT generated by a route remembers which route + item created
-- it. Lets the OT detail surface a "Generada por ruta" banner and lets the
-- rollup PDF group sub-OTs by route.
ALTER TABLE public.ordenes_trabajo
  ADD COLUMN IF NOT EXISTS inspection_route_id uuid REFERENCES public.inspection_routes(id) ON DELETE SET NULL,
  ADD COLUMN IF NOT EXISTS inspection_route_item_id uuid REFERENCES public.inspection_route_items(id) ON DELETE SET NULL;
CREATE INDEX IF NOT EXISTS idx_ot_inspection_route
  ON public.ordenes_trabajo (inspection_route_id)
  WHERE inspection_route_id IS NOT NULL;

-- ──────────────────────────────────────────────────────────────────────────
-- RPC: spawn_route_run
--   Inserts a parent OT for the route + one sub-OT per route item, all in a
--   single transaction. Returns the parent OT id so the caller can navigate
--   straight into the round. Copies each item's procedimientos (item override
--   or route default) into ot_procedimientos.
--
-- SECURITY: runs as the invoking user. RLS on ordenes_trabajo applies, so the
-- caller must have insert permission on their workspace.
-- ──────────────────────────────────────────────────────────────────────────
CREATE OR REPLACE FUNCTION public.spawn_route_run(p_route_id uuid)
RETURNS uuid
LANGUAGE plpgsql
SECURITY INVOKER
AS $$
DECLARE
  v_route          public.inspection_routes%ROWTYPE;
  v_parent_id      uuid;
  v_item           public.inspection_route_items%ROWTYPE;
  v_sub_id         uuid;
  v_now            timestamptz := now();
  v_creator        uuid;
  v_procs          uuid[];
  v_asignados      uuid[];
  v_titulo         text;
BEGIN
  SELECT * INTO v_route FROM public.inspection_routes WHERE id = p_route_id;
  IF NOT FOUND THEN
    RAISE EXCEPTION 'inspection_routes row % not found', p_route_id;
  END IF;
  IF NOT v_route.activo_flag THEN
    RAISE EXCEPTION 'route % is archived', p_route_id;
  END IF;

  v_creator := auth.uid();
  v_titulo := v_route.nombre || ' — ' || to_char(v_now, 'DD/MM/YYYY');

  -- Parent OT
  INSERT INTO public.ordenes_trabajo (
    workspace_id, creado_por, titulo, descripcion,
    tipo, tipo_trabajo, estado, prioridad,
    recurrencia, recurrencia_config,
    sociedad_id, asignados_ids,
    requiere_materiales, requiere_hoja, requiere_fotos,
    inspection_route_id,
    estado_cobro, links
  ) VALUES (
    v_route.workspace_id, v_creator, v_titulo,
    COALESCE(v_route.descripcion, ''),
    'solicitud', v_route.tipo_trabajo, 'pendiente', v_route.prioridad,
    'ninguna', NULL,
    v_route.sociedad_id, v_route.default_asignados_ids,
    v_route.requiere_materiales, v_route.requiere_hoja, v_route.requiere_fotos,
    v_route.id,
    'no_cobrable', '[]'::jsonb
  )
  RETURNING id INTO v_parent_id;

  -- One sub-OT per route item, ordered by `orden` then created_at.
  FOR v_item IN
    SELECT * FROM public.inspection_route_items
    WHERE route_id = v_route.id
    ORDER BY orden ASC, created_at ASC
  LOOP
    v_procs := COALESCE(v_item.procedimiento_ids, v_route.default_procedimiento_ids);
    v_asignados := COALESCE(v_item.asignados_ids, v_route.default_asignados_ids);

    INSERT INTO public.ordenes_trabajo (
      workspace_id, creado_por, titulo, descripcion,
      tipo, tipo_trabajo, estado, prioridad,
      recurrencia, recurrencia_config,
      parent_id, activo_id, sociedad_id,
      ubicacion_id,
      asignados_ids,
      requiere_materiales, requiere_hoja, requiere_fotos,
      inspection_route_id, inspection_route_item_id,
      estado_cobro, links
    )
    SELECT
      v_route.workspace_id, v_creator,
      a.nombre,                          -- sub-OT title defaults to the activo name
      COALESCE(v_item.notas, ''),
      'solicitud', v_route.tipo_trabajo, 'pendiente', v_route.prioridad,
      'ninguna', NULL,
      v_parent_id, v_item.activo_id, v_route.sociedad_id,
      a.ubicacion_id,
      v_asignados,
      v_route.requiere_materiales, v_route.requiere_hoja, v_route.requiere_fotos,
      v_route.id, v_item.id,
      'no_cobrable', '[]'::jsonb
    FROM public.activos a
    WHERE a.id = v_item.activo_id
    RETURNING id INTO v_sub_id;

    -- Attach procedimientos (one ot_procedimientos row per proc id).
    IF v_procs IS NOT NULL AND array_length(v_procs, 1) IS NOT NULL THEN
      INSERT INTO public.ot_procedimientos (orden_id, procedimiento_id)
      SELECT v_sub_id, p FROM unnest(v_procs) AS p
      WHERE p IS NOT NULL;
    END IF;
  END LOOP;

  RETURN v_parent_id;
END;
$$;

-- RLS policies (mirror activos: workspace-scoped read/write, admin-tier delete).
ALTER TABLE public.inspection_routes ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.inspection_route_items ENABLE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS inspection_routes_select ON public.inspection_routes;
DROP POLICY IF EXISTS inspection_routes_insert ON public.inspection_routes;
DROP POLICY IF EXISTS inspection_routes_update ON public.inspection_routes;
DROP POLICY IF EXISTS inspection_routes_delete ON public.inspection_routes;

CREATE POLICY inspection_routes_select ON public.inspection_routes
  FOR SELECT TO authenticated
  USING (workspace_id = public.my_workspace_id());
CREATE POLICY inspection_routes_insert ON public.inspection_routes
  FOR INSERT TO authenticated
  WITH CHECK (workspace_id = public.my_workspace_id());
CREATE POLICY inspection_routes_update ON public.inspection_routes
  FOR UPDATE TO authenticated
  USING (workspace_id = public.my_workspace_id())
  WITH CHECK (workspace_id = public.my_workspace_id());
CREATE POLICY inspection_routes_delete ON public.inspection_routes
  FOR DELETE TO authenticated
  USING (
    workspace_id = public.my_workspace_id()
    AND (SELECT rol FROM public.usuarios WHERE id = auth.uid() LIMIT 1)
        IN ('admin', 'owner', 'supervisor')
  );

DROP POLICY IF EXISTS inspection_route_items_select ON public.inspection_route_items;
DROP POLICY IF EXISTS inspection_route_items_insert ON public.inspection_route_items;
DROP POLICY IF EXISTS inspection_route_items_update ON public.inspection_route_items;
DROP POLICY IF EXISTS inspection_route_items_delete ON public.inspection_route_items;

-- Items inherit the parent route's workspace via the FK.
CREATE POLICY inspection_route_items_select ON public.inspection_route_items
  FOR SELECT TO authenticated
  USING (EXISTS (
    SELECT 1 FROM public.inspection_routes r
    WHERE r.id = route_id AND r.workspace_id = public.my_workspace_id()
  ));
CREATE POLICY inspection_route_items_insert ON public.inspection_route_items
  FOR INSERT TO authenticated
  WITH CHECK (EXISTS (
    SELECT 1 FROM public.inspection_routes r
    WHERE r.id = route_id AND r.workspace_id = public.my_workspace_id()
  ));
CREATE POLICY inspection_route_items_update ON public.inspection_route_items
  FOR UPDATE TO authenticated
  USING (EXISTS (
    SELECT 1 FROM public.inspection_routes r
    WHERE r.id = route_id AND r.workspace_id = public.my_workspace_id()
  ));
CREATE POLICY inspection_route_items_delete ON public.inspection_route_items
  FOR DELETE TO authenticated
  USING (EXISTS (
    SELECT 1 FROM public.inspection_routes r
    WHERE r.id = route_id AND r.workspace_id = public.my_workspace_id()
  ));;
